os: linux
dist: bionic
language: python
env:
  global:
    - CURRENT_CANARY_VERSION=0.0.1
    - CI_NODE_TOTAL=2
  # jobs:
  #   - CI_NODE_INDEX=0
  #   - CI_NODE_INDEX=1
# compiler:
#   - clang
#   - gcc

# Define your installation scripts here
# install:
  # - "[ $CXX = g++ ] && export CXX=g++-6 || true"
  # - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"

# Define your test scripts here
script:
  # - g++ --version
  - python3 --version
  # - make
